In [2]:
from sklearn.datasets import fetch_olivetti_faces
X, y = fetch_olivetti_faces(return_X_y=True)
X.shape, y.shape

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to C:\Users\fabio\scikit_learn_data


((400, 4096), (400,))

In [3]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, random_state=42)
X_tr.shape, X_te.shape, y_tr.shape, y_te.shape

((300, 4096), (100, 4096), (300,), (100,))

In [6]:
#testando o classificador KNN
from sklearn.neighbors import KNeighborsClassifier
modelo = KNeighborsClassifier()
modelo.fit(X_tr, y_tr)
knn_pr = modelo.predict(X_te)
knnhits = knn_pr == y_te
knnhits, sum(knnhits)/len(knnhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True, False, False,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.83)

In [7]:
# testando com outros classificadores
# Naive bayes da UCI

from sklearn.naive_bayes import GaussianNB
modelo = GaussianNB()
modelo.fit(X_tr, y_tr)
gnb_pr = modelo.predict(X_te)
gnbhits = gnb_pr == y_te
gnbhits, sum(gnbhits)/len(gnbhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
        False]),
 0.81)

In [8]:
# testando com o classificador perceptrom
from sklearn.linear_model import Perceptron
modelo = Perceptron()
modelo.fit(X_tr, y_tr)
per_pr = modelo.predict(X_te)
perhits = per_pr == y_te
perhits, sum(perhits)/len(perhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True, False,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True, False,  True,  True,
        False]),
 0.78)

In [9]:
import numpy as np
hits = np.stack((knnhits, gnbhits, perhits))
hits.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ T

In [10]:
y_pr = np.stack((knn_pr, gnb_pr, per_pr))
y_pr.T

array([[20, 20, 20],
       [28, 28, 28],
       [ 3,  3,  3],
       [21, 21, 21],
       [ 9,  9,  9],
       [ 8,  8,  8],
       [32, 32, 32],
       [ 9,  9,  9],
       [26, 26, 26],
       [12, 16, 28],
       [ 0,  0,  0],
       [36, 36, 36],
       [ 5,  5,  8],
       [ 7, 15,  7],
       [13, 13, 13],
       [ 4, 34, 29],
       [25, 27, 25],
       [37, 37, 37],
       [23, 23, 23],
       [38, 38, 38],
       [ 7, 15,  7],
       [ 1,  1,  1],
       [ 4, 39, 39],
       [25, 27, 25],
       [ 0,  0,  0],
       [ 3, 39, 39],
       [11, 11, 11],
       [22, 22, 22],
       [26, 26, 26],
       [10, 15, 10],
       [29, 39, 39],
       [29, 19, 19],
       [26, 26, 26],
       [ 5,  5, 29],
       [20, 23, 23],
       [11, 11, 11],
       [12, 39, 11],
       [20, 34, 34],
       [15, 15, 15],
       [14, 14, 14],
       [38, 38, 38],
       [ 5,  5, 29],
       [ 7,  9,  7],
       [ 2,  2, 36],
       [ 8,  8,  8],
       [28, 38, 28],
       [14, 14, 14],
       [18, 1

In [11]:
# COMBINAÇÃO DOS CLASSIFICADORES
from scipy import stats
y_pr = stats.mode(y_pr)[0][0]
vohits = y_pr == y_te  #acertos do hits
vohits, sum(vohits)/len(vohits)


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

In [12]:
# combinação de classificadores

In [15]:
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier([
('knn', KNeighborsClassifier()),
('naivebayes', GaussianNB()),
('perceptron', Perceptron())
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

In [16]:
# verificar se o classificador é bom ou ruim usando uma arvore de decisao e comparando a acurácia
from sklearn.tree import DecisionTreeClassifier
modelo = VotingClassifier([
('knn', KNeighborsClassifier()),
('naivebayes', GaussianNB()),
('arvore', DecisionTreeClassifier())
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.82)

In [ ]:
# o knn faz 83 sozinho, junto com a arvore de decisões ele cai para 81


In [20]:
# testando a arvore sozinha 
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
dt_pr = modelo.predict(X_te)
dthits = dt_pr == y_te
dthits, sum(dthits)/len(dthits)


(array([False,  True, False,  True,  True, False,  True,  True,  True,
        False, False,  True,  True, False, False, False, False, False,
         True, False,  True, False, False, False, False, False, False,
        False,  True, False, False,  True, False, False, False, False,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False,  True, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False, False,  True,  True, False, False, False,  True, False,
        False, False,  True,  True, False, False, False,  True, False,
        False, False,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False, False,  True, False,
        False]),
 0.4)

In [ ]:
# conclusão: a arvore de decisões sozinha é um classificador ruim.

In [ ]:
# diversificação por reamostragem
# solução: implementar o algoritmo Baggin

In [21]:
from sklearn.ensemble import BaggingClassifier
modelo = BaggingClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
bgg_pr = modelo.predict(X_te)
bgghits = bgg_pr == y_te
bgghits, sum(bgghits)/len(bgghits)


(array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False,  True,  True, False,  True, False, False,  True,
         True,  True, False,  True, False, False,  True, False,  True,
         True,  True,  True, False,  True,  True,  True, False, False,
        False,  True, False, False, False,  True, False,  True, False,
         True,  True,  True,  True, False, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False,  True, False,  True, False,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,
        False]),
 0.64)

In [ ]:
# mesmo um classificador ruim, ele pode se tornar melhor estando 
# junto com vários classificadores bons
# aumentando a aleatoriedade aumenta a diversidade, como faz isso? 

In [23]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), random_state=42)
modelo.fit(X_tr, y_tr)
bgg_pr = modelo.predict(X_te)
bgghits = bgg_pr == y_te
bgghits, sum(bgghits)/len(bgghits)

(array([ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False, False,  True,
         True,  True,  True, False,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True, False,  True, False,  True,  True,
        False,  True,  True, False,  True, False,  True,  True, False,
         True, False, False,  True, False,  True,  True,  True, False,
        False,  True, False,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True]),
 0.72)

In [ ]:
# 0.72 = aumento de acurácia ficou melhor com o aleatório
# aumentar o numero de árvores também melhora a acurácia,
# o agoritmo bagg ja tem um padrão de 10 arvores, no proximo codigo 
# vamos criar 100 arvores: n_estimaters=100


In [27]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), 
n_estimators=100, random_state=42)
modelo.fit(X_tr, y_tr)
bgg_pr = modelo.predict(X_te)
bgghits = bgg_pr == y_te
bgghits, sum(bgghits)/len(bgghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.89)

In [ ]:
# acurácia melhorou mas ainda não chegou na combinação dos três primeiros
# Random Forest é um bagging de Arvores de decisão

In [28]:
from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
rf_pr = modelo.predict(X_te)
rfhits = rf_pr == y_te
rfhits, sum(rfhits)/len(rfhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.88)

In [ ]:
# Resultado parecido porém de forma mais rápida
# como regularizar o baggin? limitando as caracteristicas

In [29]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), 
n_estimators=100, max_features=0.15, random_state=42) # gerando over fit # para cada arvore ele esta usando 15% de cada caracteristica e o treinamento foi mais rápido
modelo.fit(X_tr, y_tr)
bgg_pr = modelo.predict(X_te)
bgghits = bgg_pr == y_te
bgghits, sum(bgghits)/len(bgghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.94)

In [ ]:
# para cada arvore ele esta usando 15% de cada caracteristica e o treinamento foi mais rápido

# Florestas extremamente aleatórias


In [30]:
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
et_pr = modelo.predict(X_te)
ethits = et_pr == y_te
ethits, sum(ethits)/len(ethits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

In [ ]:
# um resultado um pouco melhor
# outra forma é aplicar o algoritmo boosting:

In [31]:
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
aboos_pr = modelo.predict(X_te)
abooshits = aboos_pr == y_te
abooshits, sum(abooshits)/len(abooshits)

(array([False, False, False, False, False, False,  True, False, False,
        False, False, False,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
         True, False,  True, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False,  True, False,
        False]),
 0.13)

In [ ]:
# ajustar as caracteristicas para aumentar a acurácia:
# ele depende de ajustes e parâmetros pois sozinho tenho desempenho baixo
# um ajuste que pode ser feito é o max_depht profundidade maxima da arvore
# outro é o splitter randomico
# taxa de aprendizado: learning

In [35]:
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(DecisionTreeClassifier(max_depth=25,
splitter='random'), learning_rate=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
aboos_pr = modelo.predict(X_te)
abooshits = aboos_pr == y_te
abooshits, sum(abooshits)/len(abooshits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.91)

In [ ]:
# o teste melhorou porque os parâmetros foram superajustados mas
# não funcionaria se fosse jogar direto em um ambiente de produção

In [43]:
# Algoritmo Xgboost
import xgboost as xgb
from xgboost import XGBClassifier
modelo = XGBClassifier(use_lebel_encoder=False, random_state=42)
modelo.fit(X_tr, y_tr)
xgbs_pr = modelo.predict(X_te)
xgbshits = xgbs_pr == y_te
xgbshits, sum(xgbshits)/len(xgbshits)

ImportError: cannot import name 'XGBClassifier' from 'xgboost' (unknown location)

In [44]:
# ajustar as característica do xgboost

import xgboost as xgb
from xgboost import XGBclassifier
modelo = XGBClassifier(colsemple_bynode=0.01, learn_rate=0.15,
random_state=42)
modelo.fit(X_tr, y_tr)
xgbs_pr = modelo.predict(X_te)
xgbshits = xgbs_pr == y_te
xgbshits, sum(xgbshits)/len(xgbshits) 

ImportError: cannot import name 'XGBclassifier' from 'xgboost' (unknown location)

In [ ]:
# ativar xgboost?
# ultimo 

In [45]:
import warnings
warnings.filterwarnings('ignore')

In [55]:
# algoritmo Stacking com ajustes 

from sklearn.ensemble import StackingClassifier
voting = VotingClassifier([
('knn', KNeighborsClassifier()),
('naivebayes', GaussianNB()),
('perceptron', Perceptron())
])

modelo = StackingClassifier([
('voting', voting),
('extratrees', ExtraTreesClassifier(random_state=42)),
('randomforest', RandomForestClassifier(random_state=42))
], cv=3, passthrough=True)
modelo.fit(X_tr, y_tr)
sc_pr = modelo.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

In [ ]:
# com o cv=3 o resultado foi pior, para ver se melhora usei o passthrough=True e isso melhorou para 95%